export const DUPLICATE_USERNAME_CODE = 4000
export const INACTIVITY_TIMEOUT_CODE = 4001
export const SERVER_ERROR_CODE = 4004
export const DISCONNECTED = 1001
export const SERVER_SHUTDOWN = 4005
